# Generated by Django 4.1.4 on 2022-12-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='List of badges that this user has aquired.\n', to='users.userbadges', verbose_name='Badges'),
        ),
    ]
