# Generated by Django 4.1.7 on 2023-02-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="This is the user's age,                                         calculated by its birth date.", null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banned',
            field=models.BooleanField(default=False, help_text='Boolean field that indicates if this user                                     has being banned.', verbose_name='Banned'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, help_text="This is the user's bio,                                     a quick description about them.", max_length=200, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="This is the user's birth date,                                     used for calculating its age", null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, help_text="This is the user's company,                                 if working anywhere.", max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_color',
            field=models.CharField(default='#1488ac', help_text="This is the profile page's cover color,                                     can be customized by the user. Field uses HEX colors", max_length=7, verbose_name='Cover Color'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Boolean value if user                                             has confirmed its email address', verbose_name='Email Confirmed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('NI', 'Not Informed'), ('M', 'Male'), ('F', 'Female'), ('NB', 'Non Binary')], default='NI', help_text="This is the user gender,                                 it's optional and defaults to NI.", max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Português (Brasil)')], default='pt-br', help_text="This is the user's language,                                     can be used to communicate and / or translate the website", max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(blank=True, help_text="This is the user's locale,                                 used to filter by city.", max_length=80, null=True, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='must_reset_password',
            field=models.BooleanField(default=False, help_text='Boolean field that indicates if                                                 this user must reset its password before                                                     logging in.', verbose_name='Must Reset Password'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_color',
            field=models.CharField(default='#0b1524', help_text="This is the user's primary color,                                         can be used in the website and can be customized                                             by the user. Field uses HEX colors", max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='recovery_key',
            field=models.CharField(blank=True, editable=False, help_text="This is the user's recovery key                                         used in password and account recovery process.", max_length=25, null=True, verbose_name='Recovery Key'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_color',
            field=models.CharField(default='#c7c7c5', help_text="This is the user's secondary color,                                         can be used in the website and can be customized                                             by the user. Field uses HEX colors", max_length=7, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, error_messages={'unique': 'Slug is already owned by another user.                                 Please use another'}, help_text='This is a unique field used to reference each user.                                 This is auto generated.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(blank=True, editable=False, error_messages={'unique': 'Tag is already owned by another user.                                             Please use another'}, help_text="This is the user's tag, is the same as its ID.                                 This is auto-generated", max_length=50, null=True, unique=True, verbose_name='Tag'),
        ),
    ]
