# Generated by Django 4.1.4 on 2022-12-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ips',
        ),
        migrations.DeleteModel(
            name='UserUsedIP',
        ),
    ]
