# Generated by Django 4.1.4 on 2022-12-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_ips_delete_userusedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="This is the user's birth date, used for calculating its age", null=True, verbose_name='Birth Date'),
        ),
    ]
