# Generated by Django 4.1.4 on 2023-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/person-8x.png', help_text="User's profile picture", null=True, upload_to='users/%Y/%m/%d', verbose_name=''),
        ),
    ]
