@echo off
set /A isNewInstall = 0
if exist .\venv\ (
    echo venv path already exists, ignoring...
) else (
    set /A isNewInstall = 1
    echo venv path does not exist, creating...
    python -m venv venv
)
echo Enabling virtual environment...
call .\venv\Scripts\activate
if %isNewInstall% equ 1 (
    echo Updating pip and requirements...
    pip install --upgrade setuptools wheel
    python -m pip install --upgrade pip
    echo Installing and updating requirements...
    pip install --upgrade -r .\back-end_requirements.txt
)
echo Checking project...
python .\manage.py check
echo Making Migrations...
python .\manage.py makemigrations
echo Migrating...
python .\manage.py migrate
echo Collecting static files...
python .\manage.py collectstatic --no-input
echo Starting back-end in 'localhost:8000'...
python .\manage.py runserver localhost:8000 --insecure