# Generated by Django 4.1.4 on 2022-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admins', '0002_alter_apiadmin_token_alter_apiadmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiadmin',
            name='token',
            field=models.CharField(blank=True, error_messages={'unique': 'This API token is already taken, please use another.'}, help_text='This is the API Authentication token, keep in production safe.', max_length=255, null=True, unique=True, verbose_name='API Token'),
        ),
    ]
