name: Django Validation

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade -r source/back-end/back-end_requirements.txt
    - name: Setup Project
      run: |
        python source/back-end/manage.py makemigrations
        python source/back-end/manage.py migrate
        python source/back-end/manage.py collectstatic --no-input
    - name: Check Project
      run: |
        python source/back-end/manage.py check
    - name: Run Tests
      run: |
        python source/back-end/manage.py test
