name: Django Validation

on:
  push:
    branches: [ "development", "production" ]
  pull_request:
    branches: [ "development", "production" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r source/requirements.txt
    - name: Setup Project
      run: |
        python source/back-end/manage.py makemigrations
        python source/back-end/manage.py migrate
        python source/back-end/manage.py collectstatic --no-input
    - name: Check Project
      run: |
        python source/back-end/manage.py check
    - name: Run Tests
      run: |
        python source/back-end/manage.py test
