name: Pylint Back-end

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pylint
        pip install --upgrade -r source/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
